name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i --force
    - run: CI=false npm run build --if-present --force

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install --force

    - name: Build the project
      run: npm run build --if-present

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Optional: Specify the folder where your built site is located (e.g., `dist` or `build` folder)
        folder: ./build
        # GitHub Pages target branch (usually `gh-pages`)
        target-branch: gh-pages
        # GitHub token for authentication, will be auto-generated for you
        github_token: ${{ secrets.GITHUB_TOKEN }}
